name: learn-github-actions

on:
  push:
    branches:
      - main
      - dev
      - prod

jobs:
  dev-stg-deployments:
    name: dev & stage deployment
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Set env vars for Develop
        if: endsWith(github.ref, '/dev')
        run: |
          echo "APP_NAME=dev-partner-pos" >> $GITHUB_ENV
          echo "RETRY_FUNCTION_NAME=retryOrder" >> $GITHUB_ENV
          echo "CORE_BACKEND_BASEURL=https://api-partner.dev.cheq.io" >> $GITHUB_ENV
          echo "OFFLINE_ORDER_COLLECTION=offline_orders" >> $GITHUB_ENV
          echo "SLACK_CHANNEL=dev-deployments" >> $GITHUB_ENV
        
      - name: create env json
        run:  echo "Create Env"
        
      - name: clear env configs
        run:  echo "Clear Env Configs"
        
      - name: set env configs
        run:  echo "ENV is set"

  prod-deployment:
    name: Approval Section
    runs-on: ubuntu-latest
    environment:
      name: production    
    steps:
      - name: set env configs      
        run: echo "Approval Has Been Processed"


#jobs:
#  testing:
#    name: print hello world
#    runs-on: ubuntu-latest
#    steps:
#      - uses: trstringer/manual-approval@v1
#        with:
#          secret: ${{ secrets.APPROVAL_TOKEN }}
#          approvers: MizanIftee      
#      - run: echo "hello World"

#  Deployment:
#    name: Approval Section
#    runs-on: ubuntu-latest
#    environment:
#      name: production    
#    steps:
#      - run: echo "Approval Has Been Processed"