name: learn-github-actions
on:
  push:
    branches:
      - main
      - prod
jobs:
  testing:
    name: print hello world
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello World"

  Deployment:
    name: Approval Section
    runs-on: ubuntu-latest
    environment:
      name: production    
    steps:
      - run: echo "Approval Has Been Processed"